name: CI Pipeline

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 15.x with npm 7.x
        uses: actions/setup-node@v3
        with:
          node-version: '15'

      - name: Install correct NPM version
        run: npm install -g npm@7

      - name: Run CI steps
        working-directory: ./codebase/rdicidr-0.1.0
        run: |
          npm install
          npm run lint
          npm run prettier -- --write
          CI=true npm run test
          npm run build
